load binary shaders (spv)
openscenegraph/OpenSceneGraph pull request #1054
Opened 2021-03-16 13:10 UTC by barnoy1

Allow openscenegraph to load binary shader  (*.spv)
This PR also include a sample (osgbinaryshader) in which we load a binary shader or source code (text file).
The sample contains two light source and a model (cube) using a simple blinn-phong model shading implementation
 
![image](https://user-images.githubusercontent.com/6884303/111313832-7b1b3200-8669-11eb-92db-368818c812aa.png)

2021-03-16 15:36 UTC, LaurensVoerman commented
Looking trough the diff I see a few problems:

1> this will only work on windows:

examples/osgbinshader/osgbinshader.cpp

#include "C:/Program Files/NVIDIA Corporation/NvToolsExt/include/nvToolsExt.h"

2> whats this GLEW dependency?

GLEW is added as a required dependency in a way that only works on
windows; while (as far as I can see) it's not used at all

3> examples/osgbinshader/osgbinshader.cpp refers to data files with
"../../../examples/osgbinshader/" path

cube.obj is not submitted at all,

And if there is no cube.obj in that path the user gets the very
unhelpful "Unable to load model from command line."


Regards, Laurens.



On Tue, Mar 16, 2021 at 2:10 PM barnoy1 ***@***.***> wrote:

> Allow openscenegraph to load binary shader (*.spv)
> This PR also include a sample (osgbinaryshader) in which we load a binary
> shader or source code (text file).
> The sample contains two light source and a model (cube) using a simple
> blinn-phong model shading implementation
>
> [image: image]
> <https://user-images.githubusercontent.com/6884303/111313832-7b1b3200-8669-11eb-92db-368818c812aa.png>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/openscenegraph/OpenSceneGraph/pull/1054
> Commit Summary
>
>    - load binary shaders
>    - remove shader data from sample, reorg shader.cpp
>
> File Changes
>
>    - *M* CMakeLists.txt
>    <https://github.com/openscenegraph/OpenSceneGraph/pull/1054/files#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20a>
>    (25)
>    - *M* examples/CMakeLists.txt
>    <https://github.com/openscenegraph/OpenSceneGraph/pull/1054/files#diff-940e5356fa1137e646ea135a6f68cacbfad4fe7124c3a69163468f588acf9283>
>    (4)
>    - *A* examples/osgbinshader/CMakeLists.txt
>    <https://github.com/openscenegraph/OpenSceneGraph/pull/1054/files#diff-8a7b29b03e8ad24aeed6509b26c5e818669f9ddf79fa16e9e4202d5d16897e16>
>    (6)
>    - *A* examples/osgbinshader/compile_shaders.bat
>    <https://github.com/openscenegraph/OpenSceneGraph/pull/1054/files#diff-99269a0a0b6b8260e06829174ab34f6a4e03b08aa3912b1b0831a3a0330a2729>
>    (5)
>    - *A* examples/osgbinshader/osgbinshader.cpp
>    <https://github.com/openscenegraph/OpenSceneGraph/pull/1054/files#diff-beec5fd3b8c0ccdc2d662ec4ce938300904b9d539bb94226a8a404e44daedb61>
>    (316)
>    - *A* examples/osgbinshader/pass_through.frag
>    <https://github.com/openscenegraph/OpenSceneGraph/pull/1054/files#diff-7bcce14d9529f55e2eeaa672afc3efdd3c00e6ec540ab3ec4cd0bbda7adda0ff>
>    (21)
>    - *A* examples/osgbinshader/pass_through.vert
>    <https://github.com/openscenegraph/OpenSceneGraph/pull/1054/files#diff-f658dd7f597a3200b98856e73d523920048627b9ed4ddd7605f3de1bdf40d86b>
>    (28)
>    - *A* examples/osgbinshader/pass_through_frag.spv
>    <https://github.com/openscenegraph/OpenSceneGraph/pull/1054/files#diff-41080342a27fdf6ee0e3bb6bdaac3465830d80725652905e0e2e0e2a274d558b>
>    (0)
>    - *A* examples/osgbinshader/pass_through_vert.spv
>    <https://github.com/openscenegraph/OpenSceneGraph/pull/1054/files#diff-829b73d635696ef4b5294852f67e86714c2ce9aaf3d04dec9e44a8ad62e9065b>
>    (0)
>    - *A* examples/osgbinshader/rockwall.png
>    <https://github.com/openscenegraph/OpenSceneGraph/pull/1054/files#diff-28b39a5b5f46b96936af4b21645c85124c237ddf4be7ec1fd58a2e3522caad55>
>    (0)
>    - *A* examples/osgbinshader/shader.frag
>    <https://github.com/openscenegraph/OpenSceneGraph/pull/1054/files#diff-7a33be7ec27f31303cfec055f6a2c36def9597036217b19d5aedf266748c117e>
>    (60)
>    - *A* examples/osgbinshader/shader.vert
>    <https://github.com/openscenegraph/OpenSceneGraph/pull/1054/files#diff-b9f124214527fcc9b67202466cc520a323974c224045472072a8313f3c186522>
>    (44)
>    - *A* examples/osgbinshader/shader_frag.spv
>    <https://github.com/openscenegraph/OpenSceneGraph/pull/1054/files#diff-839ac8f1cd6b4ad867138bb5dddb7eabb9655d2fb0253006cdc2ec8f139eac39>
>    (0)
>    - *A* examples/osgbinshader/shader_vert.spv
>    <https://github.com/openscenegraph/OpenSceneGraph/pull/1054/files#diff-6643c9244e974f18641ce3c7bed3959aa4dca6f3109240c293173f0335958a55>
>    (0)
>    - *M* include/osg/GLExtensions
>    <https://github.com/openscenegraph/OpenSceneGraph/pull/1054/files#diff-e1f109ca1d7156d3c436e572939f5473537782bb58af3f44423e5d3431ee14b6>
>    (3)
>    - *M* include/osg/Matrixd
>    <https://github.com/openscenegraph/OpenSceneGraph/pull/1054/files#diff-44cd7114e12da52c52426c259588712bda4d65b486ea5d447524a80a0c812031>
>    (10)
>    - *M* include/osg/Matrixf
>    <https://github.com/openscenegraph/OpenSceneGraph/pull/1054/files#diff-696bd3445be77cd34d9729aad64248af04d36491690b8b0fbdafdf4c7c6bfc7e>
>    (9)
>    - *M* src/osg/GLExtensions.cpp
>    <https://github.com/openscenegraph/OpenSceneGraph/pull/1054/files#diff-45b8775cb821227b3a3a042c341f22887692dd74b7c349fe2034220356964d39>
>    (4)
>    - *M* src/osg/Shader.cpp
>    <https://github.com/openscenegraph/OpenSceneGraph/pull/1054/files#diff-e245422a928c8ca49fae3aae3bf34caaeab340e1fe60c6cb3823318a5db662f1>
>    (631)
>
> Patch Links:
>
>    - https://github.com/openscenegraph/OpenSceneGraph/pull/1054.patch
>    - https://github.com/openscenegraph/OpenSceneGraph/pull/1054.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/openscenegraph/OpenSceneGraph/pull/1054>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEXFTWWHHZGQ4B6QW6QJK5LTD5KFPANCNFSM4ZIQWNUQ>
> .
>

2021-03-16 22:00 UTC, glebm requested changes
Thanks for your contribution! I've left a few comments to save the maintainers of this repo some effort.

2021-03-18 13:14 UTC, barnoy1 commented
Hi @LaurensVoerman and @glebm ,
I would like to address the issues you mentioned in previous posts:

First I would like to reply to @LaurensVoerman post
https://github.com/openscenegraph/OpenSceneGraph/pull/1054#issuecomment-800370034
1 > I remove #include "C:/Program Files/NVIDIA Corporation/NvToolsExt/include/nvToolsExt.h"

3 > I rework the samples so now the path to the shader file (binary or source) are provided as inputs.

2 > GLEW here is need because *GL_SHADER_BINARY_FORMAT_SPIR_V_ARB* is an extension that only found when glew is included. It is need for opengl to compile the shader. The reason I put it in Shader.cpp is to be as close as possible to the extension and avoid to pollute the entire project with unnecessary include.

During the last commits I took into consideration  @glebm's comments:
1. GLEW was added via the CMake's built-in FindGLEW  I use FIND_GLEW as macro to hide *GL_SHADER_BINARY_FORMAT_SPIR_V_ARB* allowing the project to compile and work as before.
2.  #include <GL\glew.h> was changed into #include <GL/glew.h>
3.  Shader.cpp was re submitted so now it is only include the suggested changes.

2021-03-21 06:48 UTC, ronbarnoy commented on src/osg/Shader.cpp
> -        str.replace(pos, from.length(), to);
hader.cpp was re submitted so now it is only include the suggested changes.

2021-03-21 06:48 UTC, ronbarnoy commented on CMakeLists.txt
> +SET (GLEW_ROOT_DIR ${PROJECT_SOURCE_DIR}/external/glew-2.2.0)
1. As I explained [here](https://github.com/openscenegraph/OpenSceneGraph/pull/1054#issuecomment-801916905), GLEW dependency is necessary for GL_SHADER_BINARY_FORMAT_SPIR_V_ARB option.
2. GLEW was added via the CMake's built-in FindGLEW. I use FIND_GLEW as macro to hide GL_SHADER_BINARY_FORMAT_SPIR_V_ARB allowing the project to compile and work as before.

2021-03-21 06:48 UTC, ronbarnoy commented on src/osg/Shader.cpp
> +#include <GL\glew.h>
#include <GL\glew.h> was changed into #include <GL/glew.h>

2021-03-29 09:28 UTC, robertosfield commented
Just done a first pass through review.  Lots of changes.  

The OSG has gone 2 decades without needing something like GLEW as it has it's own scheme for extension checking that handles multiple contexts correctly.  We are now about add a dependency for a niche feature that can easily be properly implemented without GLEW.

This PR will not be merged with a GLEW dependency.

2021-06-24 11:37 UTC, robertosfield commented
I'm closing this PR as none of the problems raised with it have not been addressed.

2021-06-24 11:37 UTC, closed without merging